# Generated by Django 5.1 on 2024-11-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTD_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono_cliente', models.PositiveIntegerField()),
                ('comentario', models.TextField(max_length=200)),
            ],
        ),
    ]
