# Generated by Django 5.1.1 on 2024-11-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTD_App', '0002_carrito_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='session_id',
            field=models.CharField(max_length=255),
        ),
    ]
